---
# handlers file for dfir-station

- name: reload velociraptor
  systemd:
    daemon_reload: yes
    name: velociraptor

- name: reload velociraptor-client
  systemd:
    daemon_reload: yes
    name: velociraptor-client

- name: restart velociraptor
  systemd:
    state: restarted
    name: velociraptor

- name: restart velociraptor-client
  systemd:
    state: restarted
    name: velociraptor-client