#  Install and Set Up Redis
- name: Install Redis
  apt:
    name:
      - redis
    state: present
    update_cache: yes

- name: Start Redis Service
  service:
    name: redis-server.service
    state: restarted
    enabled: yes