---
# tasks file for dfor-station

# Prepare System
- name: Install CA Certificates (Debian-based systems)
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
  when: ansible_os_family == "Debian"

- name: Install Required Packages
  ansible.builtin.apt:
    name:
      - git
    state: present

- name: Upgrade Debian
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true

- name: Download Fleet From GitHub
  ansible.builtin.git:
    repo: https://github.com/fleetdm/fleet.git
    dest: "{{ fleet_install_path }}"
    clone: yes

- name: Run Fleet Docker Image
  ansible.builtin.command:
    chdir: "{{ fleet_install_path }}"
    argv:
      - docker
      - compose
      - up
      - -d