- name: Create Active Directory Domain
  microsoft.ad.domain:
    create_dns_delegation: false
    dns_domain_name: "{{ netbios_name }}.{{ fqdn_tail }}"
    domain_netbios_name: "{{ netbios_name }}"
    domain_mode: "{{ domain_functional_level }}"
    forest_mode: "{{ forest_functional_level }}"
    safe_mode_password: "{{ domain_admin_password }}"
    install_dns: true
  register: domain_creation
  failed_when:
    - domain_creation.failed
    - "domain_creation.msg is defined and \"The specified argument 'CreateDNSDelegation' was not recognized\" not in domain_cre>
  become: yes
  become_method: runas

- name: Set up Auto Logon for Administrator
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: "1"
    type: string

- name: Set DefaultUsername for Auto Logon
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUsername
    data: "Administrator"
    type: string

- name: Set DefaultPassword for Auto Logon
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: "{{ domain_admin_password }}"
    type: string

- name: Set DefaultDomainName for Auto Logon
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultDomainName
    data: "{{ netbios_name }}"
    type: string
    
- name: Ensure OpenSSH Server capability is installed
  ansible.windows.win_shell: |
    Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
  args:
    creates: "C:\\Windows\\System32\\OpenSSH\\sshd.exe"
  register: openssh_install
  failed_when: openssh_install.rc != 0 and '0x800f0922' not in openssh_install.stderr  # 0x800f0922 = already installed
  
- name: Ensure SSHD service is set to start automatically
  ansible.windows.win_service:
    name: sshd
    start_mode: auto
    state: started

- name: Reboot the Windows host
  ansible.windows.win_reboot:
    reboot_timeout: 600
    msg: "Rebooting after AD domain setup, auto-logon, and SSH configuration."
