---

- name: Install Nessus Essentials (Free) on Debian
  hosts: tenableserver
  become: yes
  tasks:

    - name: Download Nessus Package for Debian Server
      get_url:
        url: https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.8.3-debian10_amd64.deb
        dest: /tmp/Nessus.deb
        mode: '0644'

    - name: Install Nessus on Debian Server
      command: dpkg -i /tmp/Nessus.deb

    - name: Start and Enable Nessus
      ansible.builtin.systemd_service:
        name: nessusd
        state: started
        enabled: yes

    - name: Get hostname of machine to display url
      command: hostname
      register: hostname_output

    - name: Display Nessus Web URL to User
      debug:
        msg: "Access Nessus at https://{{ hostname_output }}:8834"
