---
- name: Deploy OpenVAS
  hosts: openvas
  become: yes
  tasks:
  # ------------ Install Greenbone Latest Docker Compose Image ------------

    - name: Installing Greenbone (Openvas)
      ansible.builtin.command: curl -f -O -L https://greenbone.github.io/docs/latest/_static/docker-compose.yml

    - name: Downloading Greenbone Community Container
      ansible.builtin.command: docker compose -f docker-compose.yml pull

    - name: Starting Greenbone Community Containers
      ansible.builtin.command: docker compose -f docker-compose.yml up -d
